Fix __argp_fmtstream_point()'s return type and comparisons with it
gcc -Werror=sign-compare produces:

argp-help.c:1545:15: error: comparison of integer expressions of different signedness: ‘int’ and ‘size_t’ {aka ‘long unsigned int’} [-Werror=sign-compare]
 1545 |               > __argp_fmtstream_lmargin (stream))
      |               ^

Some code seems to assume the point_col field (which __argp_fmtstream_point()
returns) can be -1, and it's an ssize_t, so this makes the function correctly
return ssize_t in all cases, and also fixes the comparison to check for the -1
case.

Signed-off-by: Peter Jones <pjones@redhat.com>